### ISSUE TITLE
NoneType has no attribute groups

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/smart_fact_crawler#18] opened 2016-11-20 01:42 UTC
Sometimes, this error is throwm by the crawler:

```
sfc.main_page().system_status 
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by dneise** [comment] 2016-11-27 11:10
closed as a dupe of #154

**Closed** 2016-11-27 11:10 UTC
